SELECT * FROM JOBRUNR_BACKGROUNDJOBSERVERS;
SELECT * FROM JOBRUNR_JOBS;
SELECT * FROM JOBRUNR_METADATA;
SELECT * FROM JOBRUNR_MIGRATIONS;
SELECT * FROM JOBRUNR_RECURRING_JOBS;
SELECT * FROM JOBRUNR_JOBS_STATS;